default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mytasks
  password: mytasks_pass

development:
  <<: *default
  database: mytasks_development

test:
  <<: *default
  database: mytasks_test

production:
  <<: *default
  database: mytasks_production
  username: mytasks
  password: <%= ENV['MYTASKS_DATABASE_PASSWORD'] %>
